package com.finance.tracker.transaction;
import com.finance.tracker.user.*; import java.math.BigDecimal; import java.time.LocalDate; import java.util.*; import java.util.stream.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @Transactional public class TransactionService { private final TransactionRepository repo;private final UserRepository users; public TransactionService(TransactionRepository repo,UserRepository users){this.repo=repo;this.users=users;}
 public List<TransactionResponse> list(Long uid,LocalDate start,LocalDate end,String category){return repo.findByUserIdOrderByDateDesc(uid).stream().filter(t->start==null||!t.getDate().isBefore(start)).filter(t->end==null||!t.getDate().isAfter(end)).filter(t->category==null||category.isBlank()||t.getCategory().equalsIgnoreCase(category)).map(this::dto).toList();}
 public TransactionResponse create(Long uid,TransactionRequest r){User u=users.findById(uid).orElseThrow(()->new IllegalArgumentException("User not found"));Transaction t=new Transaction();t.setUser(u);apply(t,r);return dto(repo.save(t));}
 public TransactionResponse update(Long uid,Long id,TransactionRequest r){Transaction t=find(uid,id);apply(t,r);return dto(t);}
 public void delete(Long uid,Long id){repo.delete(find(uid,id));}
 private Transaction find(Long uid,Long id){return repo.findByIdAndUserId(id,uid).orElseThrow(()->new IllegalArgumentException("Transaction not found"));} private void apply(Transaction t,TransactionRequest r){t.setType(r.type());t.setAmount(r.amount());t.setCategory(r.category().trim());t.setDescription(r.description());t.setDate(r.date());} private TransactionResponse dto(Transaction t){return new TransactionResponse(t.getId(),t.getType(),t.getAmount(),t.getCategory(),t.getDescription(),t.getDate());}
 public record TransactionRequest(TransactionType type,@jakarta.validation.constraints.NotNull @jakarta.validation.constraints.DecimalMin(value="0.01") BigDecimal amount,@jakarta.validation.constraints.NotBlank String category,String description,@jakarta.validation.constraints.NotNull LocalDate date){} public record TransactionResponse(Long id,TransactionType type,BigDecimal amount,String category,String description,LocalDate date){}
}
