package com.finance.tracker.budget;
import com.finance.tracker.transaction.*; import com.finance.tracker.user.*; import java.math.BigDecimal; import java.time.*; import java.util.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @Transactional public class BudgetService {private final BudgetRepository budgets;private final TransactionRepository transactions;private final UserRepository users;public BudgetService(BudgetRepository b,TransactionRepository t,UserRepository u){budgets=b;transactions=t;users=u;}
 public List<BudgetResponse> list(Long uid,int month,int year){LocalDate s=LocalDate.of(year,month,1),e=s.withDayOfMonth(s.lengthOfMonth());return budgets.findByUserIdAndMonthAndYearOrderByCategory(uid,month,year).stream().map(b->dto(b,actual(uid,b.getCategory(),s,e))).toList();}
 public BudgetResponse save(Long uid,BudgetRequest r){if(r.month()<1||r.month()>12)throw new IllegalArgumentException("Month must be between 1 and 12");Budget b=budgets.findByUserIdAndCategoryIgnoreCaseAndMonthAndYear(uid,r.category().trim(),r.month(),r.year()).orElseGet(()->{Budget x=new Budget();x.setUser(users.findById(uid).orElseThrow(()->new IllegalArgumentException("User not found")));return x;});b.setCategory(r.category().trim());b.setMonthlyLimit(r.monthlyLimit());b.setMonth(r.month());b.setYear(r.year());b=budgets.save(b);LocalDate s=LocalDate.of(r.year(),r.month(),1);return dto(b,actual(uid,b.getCategory(),s,s.withDayOfMonth(s.lengthOfMonth())));}
 public void delete(Long uid,Long id){budgets.delete(budgets.findByIdAndUserId(id,uid).orElseThrow(()->new IllegalArgumentException("Budget not found")));}
 private BigDecimal actual(Long uid,String cat,LocalDate s,LocalDate e){return transactions.findByUserIdOrderByDateDesc(uid).stream().filter(t->t.getType()==TransactionType.EXPENSE&&t.getCategory().equalsIgnoreCase(cat)&&!t.getDate().isBefore(s)&&!t.getDate().isAfter(e)).map(Transaction::getAmount).reduce(BigDecimal.ZERO,BigDecimal::add);}private BudgetResponse dto(Budget b,BigDecimal actual){return new BudgetResponse(b.getId(),b.getCategory(),b.getMonthlyLimit(),actual,b.getMonthlyLimit().signum()==0?0:actual.multiply(BigDecimal.valueOf(100)).divide(b.getMonthlyLimit(),2,java.math.RoundingMode.HALF_UP).doubleValue(),b.getMonth(),b.getYear());}
 public record BudgetRequest(@jakarta.validation.constraints.NotBlank String category,@jakarta.validation.constraints.DecimalMin(value="0.01") BigDecimal monthlyLimit,int month,int year){} public record BudgetResponse(Long id,String category,BigDecimal monthlyLimit,BigDecimal actualSpent,double percentUsed,int month,int year){}
}
